name: Build and scan Docker Image

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sysdiglabs/dummy-vuln-app:latest
    
    - name: Scan image
      id: scan
      uses: sysdiglabs/scan-action@v3
      with:
        image-tag: "sysdiglabs/dummy-vuln-app:latest"
        sysdig-secure-token: 6b976743-50c1-4d51-91cb-f141ed15d7fa
        dockerfile-path: ./Dockerfile
        input-type: docker-daemon
        run-as-user: root
        ignore-failed-scan: true
