name: Scan Image

on: [push, pull_request]

jobs:
  scan-from-registry:
    runs-on: ubuntu-latest

    steps:
      - name: Scan dummy-vuln-app from registry
        id: scan
        uses: skytube01/sysdig01@main
        with:
          # Tag of the image to analyse
          image-tag: skytube01/sysdig:latest
          # API token for Sysdig Scanning auth
          sysdig-secure-token: ${{ secrets.KUBELAB_SECURE_API_TOKEN }}
          ignore-failed-scan: true

  scan-from-docker-archive:
    runs-on: ubuntu-latest
    steps:

      - name: Pull image
        id: pull-and-save
        run: |
          docker pull skytube01/sysdig:latest
          docker save skytube01/sysdig:latest -o image.tar

      - name: Scan dummy-vuln-app from archive
        id: scan
        uses: skytube01/sysdig01@main
        with:
          # Tag of the image to analyse
          image-tag: skytube01/sysdig:latest
          # API token for Sysdig Scanning auth
          sysdig-secure-token: ${{ secrets.KUBELAB_SECURE_API_TOKEN }}
          input-type: docker-archive
          input-path: ${{ github.workspace }}/image.tar
          ignore-failed-scan: true
